✨ Add official numpy 2 support (#1503)
Support numpy 2.0.0 and greater, and fix some minor issues resulting from the update.

* Bump numpy from 1.26.4 to 2.0.1

Bumps [numpy](https://github.com/numpy/numpy) from 1.26.4 to 2.0.1.
- [Release notes](https://github.com/numpy/numpy/releases)
- [Changelog](https://github.com/numpy/numpy/blob/main/doc/RELEASE_WALKTHROUGH.rst)
- [Commits](https://github.com/numpy/numpy/compare/v1.26.4...v2.0.1)

---
updated-dependencies:
- dependency-name: numpy
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* 🚧📚 Added change to changelog
* 🩹 Fix repr issue with numpy>2 str values

This caused the following test error:
```py
FAILED glotaran/utils/test/test_io.py::test_create_clp_guide_dataset_errors - assert "Unknown clp_...'species_3')]" == "Unknown clp_... 'species_3']"

  Skipping 49 identical leading characters in diff, use -v to show
    ls are:
  -  ['species_1', 'species_2', 'species_3']
  +  [np.str_('species_1'), np.str_('species_2'), np.str_('species_3')]
```

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: s-weigand <s.weigand.phy@gmail.com>