♻️ Refactor: optimization (#1060)
* Added data provider.

* Added linked data provider.

* Save weighted data in data provider.

* Added model to dataset group.

* Added matrix provider unlinked.

* Added matrix provider linked.

* Added matrix provider linked indexdependent.

* Added estimation provider unlinked.

* Added estimation provider linked.

* Refactored matrix provider.

* Created optimizer.

* Deleted optimization calculators.

* Adapted simulation.

* Removed obsolete dataset model functions.

* Adapted megacomplexes.

* test_optimization works except full model.

* Added full model calculations.

* Made provider result methods return xarrays.

* Optimization test full model works.

* Constrain test works.

* Estimation Provider test works.

* Removed optimization grouping test

Superceded by provider tests.

* Matrix Provider test work test works.

* Fixed multiple groups test.

* Fixed relation test.

* Yesqa.

* Fixed penalty test.

* Fixed data_provider test.

* Fixed decay megacomplex finalize data.

* Fixed spectral megacomplex finalize data.

* Fixed coherent artifact test.

* Fixed doas megacomplex finalize data.

* Add global matrices to result.

* Removed dimensions from scheme.

* Fix matrix provider test.

* Fix model test.

* Fix yml scheme test.

* Fix benchmark.

* Small fix.

* Copy parameters in optimizer when setting

* 🩹 Added __future__ annotation to run python < 3.10

* Fixed adding model weight.

* Temporary disabled interrogate.

* Always save weighted_root_mean_square_error even if no weight ios present.

* Fix AVS benchmark import.

* 🩹 Fix imports in AVS benchmarks

* Added data svd to result data

* Added test for result data.

* Added model pyi.

* Fixed mypy issues in optimize module.

* ❌🧪 Deactivated mypy for tests in optimization and generators package

As discussed with @joernweissenborn those checks need to be activated again before the PR gets merged

* 👌🧪 Only check weight related data vars if expected data has weight

* ♻️ Refactored by Sourcery

* Always copy data in dataprovider.

* Transposed right singular values in resultdata.

* Added docstrings to optimize package.

* Fix bug in dataset group is_linkable.

* Addressed codesmells.

* Added model weight to resultdata.

* Addressed codesmell.

* Added weighted rms.

* Remove numba from combine_megacomplex.

* Fix bug in test_result_data.

* Added force_index_dependent to dataset model.

* Fixed is_linkable.

* Removed unecessary f strings.

* Add additional penalty to result,

* ♻️ Refactored by Sourcery

* 🧹 Removed future annotations import from pyi file

* 🩹⌨️ Fix Model.clp_area_penalties typing

* 🩹⌨️ Remove usage of 'Number' for typing

With model items and properties we use typing to do type conversion which is incompatible with 'Number' and leads to typing problems.

In [1]: from numbers import Number

In [2]: Number(1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-8247e2ac7336> in <module>
----> 1 Number(1)

TypeError: Number() takes no arguments

Mypy sees float as subclass of int, so passing an int as a flot arg is valid.

* ♻️ Refactored by Sourcery

* 🩹🧪🧹 Fixed false positive test fail and cleaned up douplicate symbols

The error was cause by 'float_resolution' not beeing the same shape as 'expected_values' and 'current_values', which was caused by using multiple symbols referencing the same value, where only 'expected_values' had a transpose save guard.

Also replaced generic Exception from bad env var with ValueError (thnx sourceryai)

* Rename global_index to global_index value when not int.

* Optimized DatasetGroup.is_linkable.

* Implemented suggestions for dataprovider.

* Implemented suggestions for estimationprovider.

* Implemented suggestions for matrixprovider.

* Activated mypy for optimization tests.

* Fixed annotation.

* Shortened docstring.

* 🧹 Removed comparison hotfix after updating gold standard

* 🩹 Adapted comparison code to work with str dataset attributes

* 🧹 Fixed code smell mentioned by codacy

* 📚🚧 Added change to changelog

Co-authored-by: s-weigand <s.weigand.phy@gmail.com>
Co-authored-by: Sourcery AI <>